@host = http://localhost:8000

### Получить токены (логин)
POST http://localhost:8000/api/auth/token/
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testpass123"
}


### Получить текущего пользователя
GET http://localhost:8000/api/user/me/
Authorization: Bearer {{access_token}}


### Продукты
GET http://localhost:8000/api/products/
Accept: application/json

### Тест корзина
GET http://localhost:8000/api/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDk2MzU4LCJpYXQiOjE3NTI0ODE5NTgsImp0aSI6IjQzZTg4MzMwZGMwODQ0ZmI4Zjk5Y2UwMDdiY2M1ZTgzIiwidXNlcl9pZCI6MX0.ZI0xdoqq5iTmK-668H3WCfTvOZoCfJDPdvh__FY65dQ

### 2. Добавить товар в корзину
POST http://localhost:8000/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDk2MzU4LCJpYXQiOjE3NTI0ODE5NTgsImp0aSI6IjQzZTg4MzMwZGMwODQ0ZmI4Zjk5Y2UwMDdiY2M1ZTgzIiwidXNlcl9pZCI6MX0.ZI0xdoqq5iTmK-668H3WCfTvOZoCfJDPdvh__FY65dQ

{
  "product_id": 1,
  "quantity": 1
}

### 3. делаем заказ
POST http://localhost:8000/api/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDk2MzU4LCJpYXQiOjE3NTI0ODE5NTgsImp0aSI6IjQzZTg4MzMwZGMwODQ0ZmI4Zjk5Y2UwMDdiY2M1ZTgzIiwidXNlcl9pZCI6MX0.ZI0xdoqq5iTmK-668H3WCfTvOZoCfJDPdvh__FY65dQ

{
  "address": "ул. Ленина, д. 10",
  "phone": "+380501234567",
  "email": "user@example.com",
  "city": "Киев",
  "delivery_type": "prepaid",
  "comments": "Будьте аккуратны"
}


### 4 Fondy
POST https://pay.fondy.eu/api/checkout/redirect/
Content-Type: application/x-www-form-urlencoded

data=eyJvcmRlcl9pZCI6ICI0MiIsICJtZXJjaGFudF9pZCI6ICIxMzk2NDI0IiwgImN1cnJlbmN5IjogIlVBSCIsICJhbW91bnQiOiAzMDgwMCwgIm9yZGVyX2Rlc2MiOiAiXHUwNDFlXHUwNDNmXHUwNDNiXHUwNDMwXHUwNDQyXHUwNDMwIFx1MDQzN1x1MDQzMFx1MDQzYVx1MDQzMFx1MDQzN1x1MDQzMCBcdTIxMTY0MiIsICJyZXNwb25zZV91cmwiOiAiaHR0cDovL2xvY2FsaG9zdDo1MTczL29yZGVyLzQyL3N1Y2Nlc3MiLCAic2VydmVyX2NhbGxiYWNrX3VybCI6ICJodHRwczovLzNlMmUxNDA5NGU1Zi5uZ3Jvay1mcmVlLmFwcC9hcGkvZm9uZHkvd2ViaG9vay8iLCAibGFuZyI6ICJ1ayJ9
&signature=e57bdf1a63e5c7ddd6a3b01f0fe266361635636c