# Generated by Django 5.2.1 on 2025-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_paymentsettings_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
