# Generated by Django 5.2.1 on 2025-06-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="Адрес не указан"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Адрес не указан", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачено"),
                    ("paid", "Оплачено"),
                    ("pending", "Ожидает"),
                    ("refunded", "Возврат"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("completed", "Завершён"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
