# Generated by Django 5.2.1 on 2025-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_novaposhtasettings_order_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novaposhtasettings",
            name="default_sender_name",
            field=models.CharField(
                blank=True,
                help_text="Имя отправителя по умолчанию",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="novaposhtasettings",
            name="sender_city_ref",
            field=models.CharField(
                blank=True,
                help_text="Ref города отправителя",
                max_length=255,
                null=True,
            ),
        ),
    ]
