# Generated by Django 5.2.1 on 2025-06-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_novaposhtasettings_default_sender_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("prepaid", "Оплата онлайн"), ("cod", "Наложенный платеж")],
                default="prepaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="warehouse_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
