# Generated by Django 5.2.1 on 2025-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
