# Generated by Django 5.2.1 on 2025-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_productimage_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_system",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("fondy", "Fondy"),
                    ("liqpay", "LiqPay"),
                    ("portmone", "Portmone"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentsettings",
            name="_sandbox",
            field=models.BooleanField(default=True, verbose_name="Песочница (sandbox)"),
        ),
        migrations.AlterField(
            model_name="paymentsettings",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активна"),
        ),
    ]
