# Generated by Django 5.2.1 on 2025-07-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_payment_payment_system_paymentsettings__sandbox_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentsettings",
            old_name="_sandbox",
            new_name="is_sandbox",
        ),
    ]
