# Generated by Django 5.2.1 on 2025-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nova_poshta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
