# Generated by Django 5.2.1 on 2025-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_nova_poshta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtasettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
