# Generated by Django 5.2.1 on 2025-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_novaposhtasettings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtasettings',
            name='auto_create_ttn',
            field=models.BooleanField(default=False, verbose_name='Автоматически создавать ТТН'),
        ),
        migrations.AddField(
            model_name='novaposhtasettings',
            name='default_seats_amount',
            field=models.PositiveIntegerField(default=1, help_text='Количество мест (посылок)'),
        ),
        migrations.AddField(
            model_name='novaposhtasettings',
            name='default_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Вес одной посылки в кг', max_digits=5),
        ),
        migrations.AddField(
            model_name='novaposhtasettings',
            name='senders_phone',
            field=models.CharField(default='0500000000', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Новая Почта'), ('self_pickup', 'Самовывоз'), ('other', 'Другое')], default='other', max_length=30),
        ),
    ]
