# Generated by Django 5.2.1 on 2025-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_novaposhtasettings_auto_create_ttn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtasettings',
            name='sender_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref(ID) отделения откуда будете отправлять'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettings',
            name='sender_city_ref',
            field=models.CharField(blank=True, help_text='Ref(ID) города отправителя, например: 8d5a980d-391c-11d...', max_length=255, null=True),
        ),
    ]
